_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("coco_2017_train_refcoco",)
  TEST: ("coco_2017_val_refcoco", "coco_2017_val")
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (195552, 232800)
  MAX_ITER: 251424
  CHECKPOINT_PERIOD: 6984
DATALOADER:
  NUM_WORKERS: 20
